const id = ['id', 'BIGINT UNSIGNED NOT NULL AUTO_INCREMENT', 'PK']
const cot = (ten, kieu = 'VARCHAR(255) NULL') => [ten, kieu]
const fk = (ten, bang, tuyChon = false) => [ten, `BIGINT UNSIGNED ${tuyChon ? 'NULL' : 'NOT NULL'}`, bang]
const ngay = ten => cot(ten, 'DATETIME(6) NULL')
const json = ten => cot(ten, 'JSON NULL')
const so = (ten, macDinh = 0) => cot(ten, `INT UNSIGNED NOT NULL DEFAULT ${macDinh}`)
const trangThai = () => cot('trang_thai', 'VARCHAR(32) NOT NULL')
const bang = (ten, cotDuLieu, rangBuoc = []) => ({ ten, cot: [id, ...cotDuLieu, ngay('created_at'), ngay('updated_at')], rangBuoc })

export const cacBang = [
  bang('tai_khoan', [cot('ho_ten'), cot('email', 'VARCHAR(191) NOT NULL'), cot('password', 'VARCHAR(255) NOT NULL'), cot('vai_tro', "ENUM('KHACH_HANG','HUAN_LUYEN_VIEN','ADMIN') NOT NULL"), trangThai(), cot('remember_token', 'VARCHAR(100) NULL')], ['UNIQUE (email)']),
  bang('ho_so_khach_hang', [fk('tai_khoan_id', 'tai_khoan'), cot('muc_tieu'), cot('kinh_nghiem'), cot('gioi_tinh', 'VARCHAR(32) NULL'), cot('ngay_sinh', 'DATE NULL'), json('thoi_gian_co_the_tap')], ['UNIQUE (tai_khoan_id)']),
  bang('ho_so_huan_luyen_vien', [fk('tai_khoan_id', 'tai_khoan'), cot('chuyen_mon'), cot('gioi_thieu', 'TEXT NULL'), cot('anh_dai_dien')], ['UNIQUE (tai_khoan_id)']),
  bang('goi_tap', [cot('ten_goi', 'VARCHAR(255) NOT NULL'), cot('gia', 'BIGINT UNSIGNED NOT NULL'), cot('co_chatbot', 'BOOLEAN NOT NULL DEFAULT FALSE'), so('so_luot_chatbot_moi_ngay'), so('so_buoi_pt'), so('thoi_han_ngay'), trangThai()], ['CHECK (thoi_han_ngay > 0)', 'CHECK ((co_chatbot = 1 AND so_luot_chatbot_moi_ngay > 0) OR (co_chatbot = 0 AND so_luot_chatbot_moi_ngay = 0))', 'CHECK (co_chatbot = 1 OR so_buoi_pt > 0)']),
  bang('dang_ky_goi_tap', [fk('khach_hang_id', 'ho_so_khach_hang'), fk('goi_tap_id', 'goi_tap'), cot('client_request_id', 'CHAR(36) NOT NULL'), cot('ma_don_payos', 'BIGINT UNSIGNED NOT NULL'), cot('ma_link_payos', 'VARCHAR(191) NULL'), cot('ten_goi_snapshot', 'VARCHAR(255) NOT NULL'), cot('gia_snapshot', 'BIGINT UNSIGNED NOT NULL'), cot('co_chatbot_snapshot', 'BOOLEAN NOT NULL'), so('so_luot_chatbot_moi_ngay_snapshot'), so('so_buoi_pt_snapshot'), so('thoi_han_ngay_snapshot'), so('so_buoi_con_lai'), trangThai(), ngay('han_thanh_toan'), ngay('kich_hoat_luc'), ngay('het_han_luc'), cot('khach_dang_dung_id', "BIGINT UNSIGNED GENERATED ALWAYS AS (CASE WHEN trang_thai = 'DANG_SU_DUNG' THEN khach_hang_id ELSE NULL END) STORED")], ['UNIQUE (ma_don_payos)', 'UNIQUE (ma_link_payos)', 'UNIQUE (khach_hang_id, client_request_id)', 'UNIQUE (khach_dang_dung_id)', 'CHECK (so_buoi_con_lai <= so_buoi_pt_snapshot)', 'INDEX (khach_hang_id, trang_thai, het_han_luc)']),
  bang('thanh_toan', [fk('dang_ky_goi_tap_id', 'dang_ky_goi_tap'), cot('ma_giao_dich', 'VARCHAR(191) NOT NULL'), cot('so_tien', 'BIGINT UNSIGNED NOT NULL'), ngay('thanh_toan_luc'), ngay('xac_minh_luc'), trangThai(), cot('ly_do_doi_soat', 'TEXT NULL'), fk('nguoi_doi_soat_id', 'tai_khoan', true), ngay('doi_soat_luc'), cot('so_tien_hoan', 'BIGINT UNSIGNED NULL'), cot('ma_hoan_tien', 'VARCHAR(191) NULL'), cot('ly_do_hoan_tien', 'TEXT NULL'), ngay('hoan_tien_luc')], ['UNIQUE (ma_giao_dich)', 'CHECK (so_tien_hoan IS NULL OR so_tien_hoan <= so_tien)']),
  bang('phan_cong_huan_luyen_vien', [fk('khach_hang_id', 'ho_so_khach_hang'), fk('huan_luyen_vien_id', 'ho_so_huan_luyen_vien'), fk('nguoi_phan_cong_id', 'tai_khoan'), ngay('bat_dau_luc'), ngay('ket_thuc_luc'), cot('ly_do_ket_thuc', 'TEXT NULL'), cot('khach_dang_phan_cong_id', 'BIGINT UNSIGNED GENERATED ALWAYS AS (CASE WHEN ket_thuc_luc IS NULL THEN khach_hang_id ELSE NULL END) STORED')], ['UNIQUE (khach_dang_phan_cong_id)', 'CHECK (ket_thuc_luc IS NULL OR ket_thuc_luc > bat_dau_luc)']),
  bang('khung_gio_huan_luyen_vien', [fk('huan_luyen_vien_id', 'ho_so_huan_luyen_vien'), cot('bat_dau_luc', 'DATETIME(6) NOT NULL'), cot('ket_thuc_luc', 'DATETIME(6) NOT NULL'), trangThai()], ['UNIQUE (huan_luyen_vien_id, bat_dau_luc)', 'CHECK (TIMESTAMPDIFF(SECOND, bat_dau_luc, ket_thuc_luc) = 3600)']),
  bang('lich_hen_huan_luyen', [fk('khach_hang_id', 'ho_so_khach_hang'), fk('huan_luyen_vien_id', 'ho_so_huan_luyen_vien'), fk('phan_cong_id', 'phan_cong_huan_luyen_vien'), fk('khung_gio_id', 'khung_gio_huan_luyen_vien'), fk('dang_ky_goi_tap_id', 'dang_ky_goi_tap'), cot('client_request_id', 'CHAR(36) NOT NULL'), cot('bat_dau_luc', 'DATETIME(6) NOT NULL'), cot('ket_thuc_luc', 'DATETIME(6) NOT NULL'), trangThai(), ngay('han_xac_nhan_dat_lich'), ngay('han_xac_nhan_hoan_thanh'), ngay('xac_nhan_luc'), ngay('tieu_hao_luc'), fk('nguoi_huy_id', 'tai_khoan', true), ngay('huy_luc'), cot('ly_do_huy', 'TEXT NULL'), fk('nguoi_dong_xu_ly_id', 'tai_khoan', true), ngay('dong_xu_ly_luc'), cot('ly_do_dong_xu_ly', 'TEXT NULL'), cot('khung_gio_dang_giu_id', "BIGINT UNSIGNED GENERATED ALWAYS AS (CASE WHEN trang_thai IN ('CHO_XAC_NHAN','DA_XAC_NHAN') THEN khung_gio_id ELSE NULL END) STORED")], ['UNIQUE (khung_gio_dang_giu_id)', 'UNIQUE (khach_hang_id, client_request_id)', 'INDEX (khach_hang_id, bat_dau_luc, ket_thuc_luc)', 'CHECK (TIMESTAMPDIFF(SECOND, bat_dau_luc, ket_thuc_luc) = 3600)']),
  bang('nhom_co', [cot('ma_nhom_co', 'VARCHAR(64) NOT NULL'), cot('ten_nhom_co', 'VARCHAR(255) NOT NULL'), cot('ten_nguon', 'VARCHAR(255) NOT NULL'), trangThai()], ['UNIQUE (ma_nhom_co)']),
  bang('bai_tap', [fk('nhom_co_id', 'nhom_co'), cot('nguon_du_lieu', 'VARCHAR(64) NULL'), cot('ma_nguon', 'CHAR(4) NULL'), cot('ten_bai_tap', 'VARCHAR(255) NOT NULL'), cot('ten_tieng_viet'), cot('bo_phan_co_the', 'VARCHAR(64) NULL'), cot('dung_cu'), cot('dung_cu_nguon'), json('huong_dan'), json('cac_buoc'), json('co_phu'), cot('co_ho_tro_nguon'), cot('anh_url'), cot('gif_url'), cot('duong_dan_anh_nguon'), cot('duong_dan_gif_nguon'), cot('ma_media_nguon', 'VARCHAR(64) NULL'), cot('ghi_cong_media'), ngay('nguon_tao_luc'), ngay('nguon_cap_nhat_luc'), trangThai()], ['UNIQUE (nguon_du_lieu, ma_nguon)', 'INDEX (nhom_co_id, trang_thai)']),
  bang('giao_an_mau', [cot('ten_giao_an', 'VARCHAR(255) NOT NULL'), cot('muc_tieu'), so('so_ngay_tap'), fk('nguoi_tao_id', 'tai_khoan'), fk('nguoi_duyet_id', 'tai_khoan', true), ngay('duyet_luc'), trangThai()]),
  bang('bai_tap_trong_giao_an_mau', [fk('giao_an_mau_id', 'giao_an_mau'), fk('bai_tap_id', 'bai_tap'), so('ngay_thu', 1), so('thu_tu', 1), so('so_hiep', 1), so('so_lan_lap', 1), so('nghi_giay'), cot('ghi_chu', 'TEXT NULL')], ['UNIQUE (giao_an_mau_id, ngay_thu, thu_tu)']),
  bang('ke_hoach_tap', [fk('khach_hang_id', 'ho_so_khach_hang'), fk('huan_luyen_vien_id', 'ho_so_huan_luyen_vien'), fk('phan_cong_id', 'phan_cong_huan_luyen_vien'), fk('giao_an_mau_id', 'giao_an_mau', true), fk('thay_the_ke_hoach_id', 'ke_hoach_tap', true), cot('ten_ke_hoach', 'VARCHAR(255) NOT NULL'), cot('muc_tieu'), trangThai(), ngay('gui_luc'), ngay('han_duyet'), ngay('duyet_luc'), cot('khach_dang_ap_dung_id', "BIGINT UNSIGNED GENERATED ALWAYS AS (CASE WHEN trang_thai = 'DANG_AP_DUNG' THEN khach_hang_id ELSE NULL END) STORED")], ['UNIQUE (khach_dang_ap_dung_id)', 'INDEX (khach_hang_id, trang_thai)']),
  bang('bai_tap_trong_ke_hoach', [fk('ke_hoach_tap_id', 'ke_hoach_tap'), fk('bai_tap_id', 'bai_tap'), so('ngay_thu', 1), so('thu_tu', 1), cot('ten_bai_tap_snapshot', 'VARCHAR(255) NOT NULL'), json('noi_dung_snapshot'), so('so_hiep', 1), so('so_lan_lap', 1), so('nghi_giay'), cot('ghi_chu', 'TEXT NULL')], ['UNIQUE (ke_hoach_tap_id, ngay_thu, thu_tu)']),
  bang('lich_tap', [fk('ke_hoach_tap_id', 'ke_hoach_tap'), fk('khach_hang_id', 'ho_so_khach_hang'), so('ngay_thu', 1), cot('ngay_tap', 'DATE NOT NULL'), trangThai()], ['UNIQUE (ke_hoach_tap_id, ngay_tap, ngay_thu)']),
  bang('phien_tap', [fk('lich_tap_id', 'lich_tap'), fk('khach_hang_id', 'ho_so_khach_hang'), ngay('bat_dau_luc'), ngay('hoan_thanh_luc'), trangThai(), cot('ghi_chu', 'TEXT NULL')], ['UNIQUE (lich_tap_id)']),
  bang('bai_tap_trong_phien', [fk('phien_tap_id', 'phien_tap'), fk('bai_tap_id', 'bai_tap'), fk('bai_tap_trong_ke_hoach_id', 'bai_tap_trong_ke_hoach'), so('thu_tu', 1), cot('ten_bai_tap_snapshot', 'VARCHAR(255) NOT NULL'), json('noi_dung_snapshot')], ['UNIQUE (phien_tap_id, thu_tu)']),
  bang('hiep_tap', [fk('bai_tap_trong_phien_id', 'bai_tap_trong_phien'), so('thu_tu', 1), so('so_lan_lap'), cot('khoi_luong_kg', 'DECIMAL(7,2) UNSIGNED NULL'), so('nghi_giay')], ['UNIQUE (bai_tap_trong_phien_id, thu_tu)', 'CHECK (thu_tu > 0)']),
  bang('ghi_chu_huan_luyen', [fk('phien_tap_id', 'phien_tap'), fk('huan_luyen_vien_id', 'ho_so_huan_luyen_vien'), fk('phan_cong_id', 'phan_cong_huan_luyen_vien'), cot('noi_dung', 'TEXT NOT NULL')]),
  bang('hoi_thoai', [fk('phan_cong_id', 'phan_cong_huan_luyen_vien'), cot('cursor_khach_da_doc', 'BIGINT UNSIGNED NULL'), cot('cursor_pt_da_doc', 'BIGINT UNSIGNED NULL')], ['UNIQUE (phan_cong_id)']),
  bang('tin_nhan', [fk('hoi_thoai_id', 'hoi_thoai'), fk('nguoi_gui_id', 'tai_khoan'), cot('client_message_id', 'CHAR(36) NOT NULL'), cot('noi_dung', 'TEXT NOT NULL')], ['UNIQUE (hoi_thoai_id, nguoi_gui_id, client_message_id)', 'INDEX (hoi_thoai_id, id)']),
  bang('hoi_thoai_tro_ly', [fk('khach_hang_id', 'ho_so_khach_hang'), cot('tieu_de'), trangThai()]),
  bang('yeu_cau_tro_ly', [fk('khach_hang_id', 'ho_so_khach_hang'), fk('hoi_thoai_tro_ly_id', 'hoi_thoai_tro_ly'), fk('dang_ky_goi_tap_id', 'dang_ky_goi_tap'), cot('client_request_id', 'CHAR(36) NOT NULL'), cot('ngay_han_muc', 'DATE NOT NULL'), cot('provider', 'VARCHAR(64) NULL'), cot('model', 'VARCHAR(128) NULL'), trangThai(), ngay('giu_luot_den'), ngay('hoan_thanh_luc'), cot('ma_loi', 'VARCHAR(64) NULL'), so('do_tre_ms'), so('input_tokens'), so('output_tokens')], ['UNIQUE (khach_hang_id, client_request_id)', 'INDEX (khach_hang_id, ngay_han_muc, trang_thai, giu_luot_den)']),
  bang('tin_nhan_tro_ly', [fk('hoi_thoai_tro_ly_id', 'hoi_thoai_tro_ly'), fk('yeu_cau_tro_ly_id', 'yeu_cau_tro_ly'), cot('vai_tro', "ENUM('USER','ASSISTANT') NOT NULL"), cot('noi_dung', 'TEXT NOT NULL'), json('nguon_da_kiem_tra')], ['UNIQUE (yeu_cau_tro_ly_id, vai_tro)', 'INDEX (hoi_thoai_tro_ly_id, id)']),
  bang('tai_lieu_tu_van', [cot('tieu_de', 'VARCHAR(255) NOT NULL'), cot('loai', 'VARCHAR(32) NOT NULL'), cot('noi_dung', 'LONGTEXT NOT NULL'), so('phien_ban', 1), fk('nguoi_cap_nhat_id', 'tai_khoan'), trangThai(), ngay('xuat_ban_luc')]),
  bang('chi_so_co_the', [fk('khach_hang_id', 'ho_so_khach_hang'), cot('ngay_ghi', 'DATE NOT NULL'), cot('can_nang_kg', 'DECIMAL(6,2) UNSIGNED NULL'), cot('chieu_cao_cm', 'DECIMAL(5,2) UNSIGNED NULL'), cot('vong_eo_cm', 'DECIMAL(5,2) UNSIGNED NULL'), cot('ghi_chu', 'TEXT NULL')], ['UNIQUE (khach_hang_id, ngay_ghi)']),
  bang('nhat_ky_he_thong', [fk('tai_khoan_id', 'tai_khoan', true), cot('hanh_dong', 'VARCHAR(128) NOT NULL'), cot('loai_tai_nguyen', 'VARCHAR(128) NOT NULL'), cot('tai_nguyen_id', 'BIGINT UNSIGNED NULL'), json('metadata_an_toan')], ['INDEX (loai_tai_nguyen, tai_nguyen_id, created_at)']),
]
